abby:
  api:
    key: ${ABBY_API_KEY:default-value}
google:
  maps:
    api:
      key: ${GOOGLE_MAPS_API_KEY:default-value}
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-secret: ${GOOGLE_CLIENT_SECRET:default-value}