google:
  drive:
    root-folder-id: 1M9zZNyjo-Zh9GDiwvfmiqGvNo1o5ExMW

spring:
  jackson:
    default-property-inclusion: non_empty
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 683700653292-7f4750iff8ujelfare6s56qbq0416jq9.apps.googleusercontent.com
abby:
  api:
    key: default-value