### Import activities of a given month from calendar
POST http://localhost:8080/activities/2024/3
Accept: application/json
Content-Type: application/json

### Import activities between 2 dates from calendar
POST http://localhost:8080/activities
Accept: application/json
Content-Type: application/json

{
  "start": "2024-11-01T00:00:00+01:00",
  "end": "2024-12-01T00:00:00+01:00"
}

### list activities between 2 dates from calendar
GET http://localhost:8080/activities?start=2024-10-01T00:00:00Z&end=2024-10-31T23:59:59Z
Accept: application/json
Content-Type: application/json